import { normalizeCourse } from '../../lib/normalize.js';

const COURSES = [
  {
    provider: 'Anthogyr International Seminar',
    provider_slug: 'anthogyr-international-seminar',
    url: 'https://www.straumann.com/anthogyr/en/home/education/training-program/international-seminar.html',
    title: 'Anthogyr Campus International Seminar',
    description: 'Two-day Anthogyr Campus journey introducing the company, Axiom range, Simeda CAD/CAM innovations, live surgery, and hands-on clinical sessions in Sallanches, France.',
    location: 'Sallanches, France',
    city: 'Sallanches',
    country: 'France',
    format: 'In Person',
    course_type: 'Seminar',
    topic: 'Implants',
    accreditation: 'Anthogyr Campus',
    tags: ['Anthogyr', 'Implants', 'France', 'International seminar'],
  },
  {
    provider: 'Anthogyr Implantologie 3.0 Paris',
    provider_slug: 'anthogyr-implantologie-3-paris',
    url: 'https://www.straumann.com/anthogyr/en/home/education/training-program.detail.course.27251.html',
    title: 'IMPLANTOLOGIE 3.0 : Poser vos premiers implants à l’ère du numérique',
    description: 'Multi-module Paris training program focused on planning, practice integration, digital implantology, guided surgery, and hands-on work with jaws in resin.',
    start_date: '2026-04-23',
    end_date: '2026-09-11',
    date_text: '23 Apr 2026 - 11 Sep 2026',
    location: 'Paris, France',
    city: 'Paris',
    country: 'France',
    price: 'EUR 4700.00',
    audience: 'National',
    format: 'In Person',
    course_type: 'Program',
    topic: 'Implants',
    accreditation: 'Anthogyr Campus',
    requirements: 'Bookable; 42 hours.',
    tags: ['Anthogyr', 'France', 'Implants', 'Digital workflow'],
  },
  {
    provider: 'Anthogyr Initiation Implantology Rennes',
    provider_slug: 'anthogyr-initiation-implantology-rennes',
    url: 'https://www.straumann.com/anthogyr/en/home/education/training-program.detail.course.28228.html',
    title: 'PROGRAMME INITIATION A L’IMPLANTOLOGIE',
    description: 'Foundational Anthogyr implantology initiation program in Rennes.',
    start_date: '2026-04-02',
    end_date: '2026-07-10',
    date_text: '02 Apr 2026 - 10 Jul 2026',
    location: 'Rennes, France',
    city: 'Rennes',
    country: 'France',
    price: 'EUR 4900.00',
    format: 'In Person',
    course_type: 'Program',
    topic: 'Implants',
    accreditation: 'Anthogyr Campus',
    requirements: 'Bookable; registration deadline 02 Apr 2026.',
    tags: ['Anthogyr', 'France', 'Implants'],
  },
  {
    provider: 'Anthogyr Intensiv Workshop Germany',
    provider_slug: 'anthogyr-intensiv-workshop-germany',
    url: 'https://www.straumann.com/anthogyr/en/home/education/training-program.detail.course.29430.html',
    title: 'Intensiv Workshop - Implantologie einfach gemacht mit Anthogyr',
    description: 'Intensive Anthogyr workshop designed to simplify implantology workflows.',
    start_date: '2026-04-18',
    end_date: '2026-04-18',
    date_text: '18 Apr 2026',
    location: 'Brühl, Germany',
    city: 'Brühl',
    country: 'Germany',
    price: 'EUR 59.00',
    format: 'In Person',
    course_type: 'Workshop',
    topic: 'Implants',
    accreditation: 'Anthogyr Campus',
    requirements: 'Fully booked.',
    tags: ['Anthogyr', 'Germany', 'Implants'],
  },
];

export async function scrapeAnthogyrSeeded() {
  console.log('   • Building Anthogyr seeded catalog from currently indexed official course pages');

  return COURSES.map((course) => normalizeCourse({
    ...course,
    source_url: course.url,
    metadata: {
      extracted_from: 'indexed-official-course-pages',
      note: 'Anthogyr live pages are access denied from this environment; seeded from currently indexed official detail pages.',
    },
  }));
}
