import { normalizeCourse } from '../../lib/normalize.js';

const COURSES = [
  {
    provider: 'Straumann Full Arch Summit Mykonos',
    provider_slug: 'straumann-full-arch-summit-mykonos',
    url: 'https://www.straumann.com/en/dental-professionals/training-and-education/local-and-international-courses.detail.course.28908.html',
    title: 'Full Arch Summit Mykonos 2026',
    description: 'Premier global implantology event focused on complications, restorative challenges, digital workflows, and full-arch rehabilitation strategies.',
    start_date: '2026-07-05',
    end_date: '2026-07-08',
    date_text: '05 Jul 2026 - 08 Jul 2026',
    location: 'Mykonos, Greece',
    city: 'Mykonos',
    country: 'Greece',
    price: 'USD 3000.00',
    audience: 'International',
    format: 'In Person',
    course_type: 'Conference / Summit',
    topic: 'Implants',
    accreditation: 'Straumann Education',
    requirements: 'Bookable; registration deadline 02 Jul 2026.',
    tags: ['Straumann', 'Full Arch', 'Implants', 'Digital Solutions', 'Greece'],
  },
  {
    provider: 'Straumann Digital Full Arch Implant Summit UCSD',
    provider_slug: 'straumann-digital-full-arch-implant-summit-ucsd',
    url: 'https://www.straumann.com/en/dental-professionals/training-and-education/local-and-international-courses.detail.course.26984.html',
    title: 'Digital Full Arch Implant Summit at UCSD',
    description: 'Two-day immersive program on structured digital protocols for guided surgery, prosthetic delivery, photogrammetry, AI-assisted treatment planning, and full-arch immediate workflows.',
    start_date: '2026-01-23',
    end_date: '2026-01-24',
    date_text: '23 Jan 2026 - 24 Jan 2026',
    location: 'San Diego, California, United States',
    city: 'San Diego',
    state: 'CA',
    country: 'USA',
    price: 'USD 2950.00',
    audience: 'National',
    format: 'In Person',
    course_type: 'Event',
    topic: 'Implants',
    accreditation: 'Straumann Education',
    requirements: 'Bookable; registration deadline 24 Jan 2026.',
    tags: ['Straumann', 'Full Arch', 'Digital Dentistry', 'Photogrammetry', 'USA'],
  },
  {
    provider: 'Straumann Full Arch Rehabilitation Lithuania',
    provider_slug: 'straumann-full-arch-rehabilitation-lithuania',
    url: 'https://www.straumann.com/us/en/dental-professionals/training-and-education/education-course-calendar.detail.course.28889.html',
    title: 'Full Arch Rehabilitation Course: surgical, prosthetic and laboratory perspectives',
    description: 'Comprehensive two-day learning experience covering diagnosis, treatment planning, surgical execution, prosthetics, and digital workflow integration for full-arch implant therapy.',
    start_date: '2026-04-16',
    end_date: '2026-04-17',
    date_text: '16 Apr 2026 - 17 Apr 2026',
    location: 'Vilnius, Lithuania',
    city: 'Vilnius',
    country: 'Lithuania',
    price: 'EUR 1950.00',
    audience: 'National',
    format: 'In Person',
    course_type: 'Classroom theoretical lecture',
    topic: 'Implants',
    accreditation: 'Straumann Education',
    requirements: 'Bookable; registration deadline 13 Apr 2026.',
    tags: ['Straumann', 'Full Arch', 'Implants', 'Lithuania', 'Europe'],
  },
  {
    provider: 'Straumann Full-Arch Digital Workflows Canada',
    provider_slug: 'straumann-full-arch-digital-workflows-canada',
    url: 'https://www.straumann.com/en/dental-professionals/training-and-education/local-and-international-courses.detail.course.29137.html',
    title: 'Full-Arch Dental Implant Rehabilitation: Advanced Surgical Principles in Digital Workflows',
    description: 'Hands-on seminar on candidate selection, digital workup, surgical planning, photogrammetry, IOS scans, CAD design, and immediate-load full-arch workflows.',
    start_date: '2026-09-18',
    end_date: '2026-09-19',
    date_text: '18 Sep 2026 - 19 Sep 2026',
    location: 'North York, Canada',
    city: 'North York',
    country: 'Canada',
    price: 'CAD 1995.00',
    audience: 'National',
    format: 'In Person',
    course_type: 'Event',
    topic: 'Implants',
    accreditation: 'Straumann Education',
    requirements: 'Bookable; registration deadline 19 Sep 2026.',
    tags: ['Straumann', 'Full Arch', 'Digital Dentistry', 'Canada'],
  },
  {
    provider: 'Straumann SMART Stockholm',
    provider_slug: 'straumann-smart-stockholm',
    url: 'https://www.straumann.com/en/dental-professionals/training-and-education/local-and-international-courses.detail.course.27786.html',
    title: 'Straumann SMART - Grundkurs i implantatkirurgi för tandläkare',
    description: 'Straumann SMART foundational implant surgery course for dentists in Stockholm.',
    start_date: '2026-08-27',
    end_date: '2026-08-29',
    date_text: '27 Aug 2026 - 29 Aug 2026',
    location: 'Stockholm, Sweden',
    city: 'Stockholm',
    country: 'Sweden',
    audience: 'National',
    format: 'In Person',
    course_type: 'Course',
    topic: 'Implants',
    accreditation: 'Straumann SMART',
    tags: ['Straumann', 'SMART', 'Implants', 'Sweden'],
  },
];

export async function scrapeStraumannSeeded() {
  console.log('   • Building Straumann Education seeded catalog from currently indexed official course pages');

  return COURSES.map((course) => normalizeCourse({
    ...course,
    source_url: course.url,
    metadata: {
      extracted_from: 'indexed-official-course-pages',
      note: 'Straumann overview pages are access denied from this environment; seeded from currently indexed official detail pages.',
    },
  }));
}
