import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "How CEAtlas Works", description: "See the CEAtlas product vision: professional CE discovery, cross-discipline matching, comparison, and travel planning in one platform." };

const journey = [
  { number: "01", title: "Start with the professional", copy: "CEAtlas organizes courses around the learner’s discipline, specialty, credit language, and renewal context.", link: "/disciplines", action: "Explore disciplines" },
  { number: "02", title: "Find credible options", copy: "Structured provider catalogs make topics, dates, formats, credits, prices, and locations easier to compare.", link: "/courses", action: "Browse the live catalog" },
  { number: "03", title: "Connect two careers", copy: "Trip Match looks for shared programs and, as catalogs expand, separate courses that overlap in place and time.", link: "/match", action: "Try Trip Match" },
  { number: "04", title: "Shortlist with confidence", copy: "Saved courses and side-by-side comparison turn scattered research into a manageable decision.", link: "/compare", action: "Open comparison" },
  { number: "05", title: "Build the trip", copy: "The selected CE becomes the anchor for flights, lodging, itinerary choices, and eventually a unified transaction.", link: "/travel", action: "Open travel planning" },
];

export default function HowItWorksPage() {
  return <div className="container vision-page">
    <section className="vision-hero"><p className="hero__eyebrow">The CEAtlas product story</p><h1>Continuing education is the reason to go. CEAtlas connects everything around it.</h1><p>Professionals currently hunt across provider calendars, board pages, conference sites, spreadsheets, and travel tabs. CEAtlas turns that fragmented process into one connected planning journey.</p><div className="hero__actions"><Link href="/match" className="button">Experience Trip Match</Link><Link href="/courses" className="button button--light">See what is live</Link></div></section>
    <section className="vision-status"><article className="vision-status__live"><p>Live foundation</p><h2>Dental CE discovery and planning</h2><ul><li>Structured course and provider catalog</li><li>Search, map, save, compare, and ratings</li><li>State guidance, cruises, packages, and travel workflows</li></ul></article><article className="vision-status__next"><p>Expansion layer</p><h2>Multi-profession network effects</h2><ul><li>Profession-specific catalogs and requirements</li><li>Shared-program and paired-course matching</li><li>Provider tools, transactions, and travel revenue</li></ul></article></section>
    <section className="vision-journey"><div className="section-heading section-heading--stacked"><p className="hero__eyebrow hero__eyebrow--dark">A connected workflow</p><h2>Browse the product in the order a customer would use it.</h2></div><div className="vision-journey__list">{journey.map((step) => <article className="vision-step card" key={step.number}><span>{step.number}</span><div><h3>{step.title}</h3><p>{step.copy}</p></div><Link href={step.link}>{step.action} →</Link></article>)}</div></section>
    <section className="vision-scenario card"><div><p className="hero__eyebrow hero__eyebrow--dark">The wedge</p><h2>A dentist and a neurosurgeon want one meaningful week away.</h2><p>Each needs relevant education. Both want the same destination and dates. Traditional CE search treats them as unrelated customers; CEAtlas recognizes the shared trip.</p></div><div className="vision-scenario__flow" aria-label="Example CEAtlas journey"><span>Dental CE</span><i>+</i><span>Medical CME</span><b>→</b><strong>One trip</strong></div></section>
    <section className="vision-business"><div className="section-heading section-heading--stacked"><p className="hero__eyebrow hero__eyebrow--dark">Why the model compounds</p><h2>Each new catalog makes the platform more useful to learners, companions, and providers.</h2></div><div className="vision-business__grid"><article className="card"><h3>More discovery intent</h3><p>Multiple professions bring more high-intent learners and more reasons to return throughout the renewal cycle.</p></article><article className="card"><h3>More match combinations</h3><p>Every new discipline increases the number of professional pairs and shared destination opportunities.</p></article><article className="card"><h3>More transaction surfaces</h3><p>Featured placement, provider tools, course transactions, travel packages, and service fees sit along the same journey.</p></article></div></section>
    <section className="vision-bridge card"><div><p className="hero__eyebrow hero__eyebrow--dark">Choose your next view</p><h2>Explore the live catalog or test the cross-discipline vision.</h2></div><div className="hero__actions"><Link href="/courses" className="button">Live dental catalog</Link><Link href="/match" className="button button-secondary">CE Trip Match</Link></div></section>
  </div>;
}
